### ISSUE TITLE
[Recipe Conflict] Bamboo Block and Bamboo Planks

### ISSUE THREAD

**Issue by Tsudico** [AllOfFabric/All-of-Fabric-2#10]
Bamboo Blocks (Bamboo Tweaks mod) and Bamboo Planks (Blockus mod) have the same recipe. This prevents any recipe using Bamboo Planks from being accessible.

**Comment by vini2003** [comment]
o no

**Comment by nonchip** [comment]
@AK9Official  there don't seem to have been any changes to either the master or dev branch regarding this lately, did you maybe forget to push the fix?

**Comment by ImAK9** [comment]
> @AK9Official there don't seem to have been any changes to either the master or dev branch regarding this lately, did you maybe forget to push the fix?

Fixed.
