### ISSUE TITLE
Plz, update RC&TR versions

### ISSUE THREAD

**Issue by drcrazy** [AllOfFabric/All-of-Fabric-2#2]
Hi, 

TechReborn version on curse has some bugs, like lighting of items storage units and fluid transfer to\from fluid storage units. And a number of other issues.

Can you use these versions, please?

https://jenkins.modmuss50.me/job/Team%20Reborn/job/RebornCore/job/1.15/87/artifact/build/libs/RebornCore-1.15-4.1.1+build.87.jar

https://jenkins.modmuss50.me/job/Team%20Reborn/job/TechReborn/job/1.15/154/artifact/build/libs/TechReborn-1.15-3.2.2+build.154.jar

**Comment by ImAK9** [comment]
fixed in next update
