### ISSUE TITLE
Can't launch the game

### ISSUE THREAD

**Issue by Leonardlasardine** [AllOfFabric/All-of-Fabric-2#28]
I have just instaled this modpack I have seen this guide :https://github.com/AllOfFabric/All-of-Fabric-2/blob/master/HOWTOINSTALL.md.
I can't launch the game. The error is 
> [17:58:59] [main/FATAL]: Mixin prepare failed preparing MixinServerPlayerEntity in sorcerycraft.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Cannot load class com.thebrokenrail.sorcerycraft.mixin.MixinServerPlayerEntity in environment type CLIENT

https://paste.ee/p/rzJmU

**Comment by ImAK9** [comment]
Is this CLIENT or SERVER?

**Comment by Leonardlasardine** [comment]
Client with MultiMc, sorry

**Comment by ImAK9** [comment]
I think I know what’s going.. Fabric Loader auto-updates because Jump Loader forces it to. 3.0.0 should be out tomorrow which fixes a hell of alot!

**Comment by ImAK9** [comment]
I knew this was kinda coming but wanted to finish 3.0 before that but life got in the way..

**Comment by Leonardlasardine** [comment]
Ah ok, I just have to wait tommorrow. it's very cool thanks

**Comment by Leonardlasardine** [comment]
Thanks, It's fine I can play
