### ISSUE TITLE
crafting quest objective does not register crafting an item

### ISSUE THREAD

**Issue by AwwShoot** [AllOfFabric/All-of-Fabric-2#29]
I cannot complete the stone torch quest despite crafting multiple stone torches using both a crafting table and a crafting station

**Comment by LemmaEOF** [comment]
Please report this to [HQM](https://github.com/shedaniel/HQM).

**Comment by shedaniel** [comment]
Shouldn't be my issue, I've tested this multiple times.

Should be related to how AOF setup the quests, if the item detection mode is precise, the amount of the item crafted matters.

For example, if you craft planks, you will get 4 back, and the quest should be set up to handle exactly 4 planks.

**Comment by ImAK9** [comment]
This is on me... Will fix in alpha 2
