### ISSUE TITLE
no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no

### ISSUE THREAD

**Issue by TheoBuzz** [AllOfFabric/All-of-Fabric-2#32]
this is stupid forge is already good this is bad fuck you delete this shit ur fabruc sucks use forge mother fuckers fabric sucks forge is perfect awesome good for mod needs no fabric is hacks hacks HACKS mixins stupid kill your self

**Comment by TheoBuzz** [comment]
bye

**Comment by vini2003** [comment]
have a wonderful day good sir

**Comment by shedaniel** [comment]
good day sir

**Comment by NinjaPhenix** [comment]
Yes fabric bad, please delete.

**Comment by shedaniel** [comment]
FIX OR REMOVE

**Comment by NinjaPhenix** [comment]
When you making the superior All of Forge?

**Comment by Maowcraft** [comment]
**Forge API** is superior to **Fabric API**
_:tiny_potato:_

**Comment by NinjaPhenix** [comment]
_Technically it kind of is_

**Comment by SuperCoder7979** [comment]
yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes

**Comment by Boundarybreaker** [comment]
christ, did this loser target every fabric project they could find lol

**Comment by Shnupbups** [comment]
"Fabric? Fabric Sucks Then It Doesn't Even Work? Not Good So 1/10" - lbt863
"bruh no warning that its cringe fabric" - mr2meows
"Game crashes. Fix or  remove." - EnderSlime_123
"fabric modding is a hell" - MORTADA KILLER0

**Comment by gregest** [comment]
remove kebab

**Comment by Sturmlilie** [comment]
![image](https://user-images.githubusercontent.com/63550306/84594223-1f5d1780-ae51-11ea-989e-9685f8792b76.png)

**Comment by TelepathicGrunt** [comment]
This kind of toxicity from forge players makes me feel like I need to port to fabric asap and leave forge for good.

**Comment by Ashley1227** [comment]
> This kind of toxicity from some forge players makes me feel like I need to port to fabric asap and leave forge for good.

@TelepathicGrunt it's probably just a troll, I wouldn't take what they say too seriously

**Comment by leumasme** [comment]
> @TelepathicGrunt it's probably just a troll, I wouldn't take what they say too seriously
nah the forge people are actually cunts. you got instantly banned from their discord if you mentioned 1.15 or fabric while forge wasnt out for 1.15 yet.

**Comment by Tschipp** [comment]
Well to be fair you also get banned if you even mention a version that is older than 1.13
