### ISSUE TITLE
Right clicking items in the air turns them into coal

### ISSUE THREAD

**Issue by TheSaucyWelshman** [AllOfFabric/All-of-Fabric-2#4]
Title basically. I've tried with vanilla and modded items, single and stacks, tools, blocks, seeds, etc. They all turn into a single piece of coal if you right click the air and turn back into the proper stack if you right click the air again.

Running the latest version of the pack on MultiMC

Edit: after right cliking a bucket in the air a few times it seems to have stopped. The bucket went onto my head at first but also turned into a piece of coal so I had the bucket in my hand and a piece of coal on my head. No clue what happened there but it seems to have fixed itself so I'll just close this for now

**Comment by emilyploszaj** [comment]
I believe you have coal equipped in the head slot (a mod adds the functionality to equip blocks and items on your head) and the mod that swaps armor with a right click is seeing that every item can be equipped in the helmet slot and is treating them like armor and swapping them.

**Comment by TheSaucyWelshman** [comment]
Ok that makes sense I guess, I'm still not sure how I equipped coal to begin with though. Maybe when I shift clicked it off my hotbar. I guess I should report that to the mod dev.

**Comment by LemmaEOF** [comment]
Likely by shift-clicking the stack to get it into your hand. That automatically puts an item in your head slot with Everything Is A Hat. It's gotten so annoying for me that I just disabled the mod.
