### ISSUE TITLE
Is running the _install_mods script still required in 2.1.1

### ISSUE THREAD

**Issue by kevinkjt2000** [AllOfFabric/All-of-Fabric-2#5]
In the 2.1.1 release notes:
> Instance now downloads all mods on first launch, aka hello Curse Points. This means that both Client & Server now has implemented Downloading on launch through Curse Forge.

Does this mean the `_install_mods` step can be skipped now?

**Comment by ImAK9** [comment]
No, server uses _install_scripts still. It downloads them through CF like on Client just with another method.

**Comment by kevinkjt2000** [comment]
The release note is confusing as it states `both Client & Server`. I was running `_install_mods.sh` before starting a server, but the release note makes me question if the mods are downloaded via CF on startup.

Do I still need to run `_install_mods.sh` before the first launch?

**Comment by ImAK9** [comment]
I should've probably explained better.. My bad! You still need to run _install_mods.sh before first launch. There is a chance I could advance on that having it being ran within the start script. I'll look into it!

**Comment by kevinkjt2000** [comment]
My question is answered. I'll leave this issue open, in case the release notes need to be updated to close it.
